### ISSUE TITLE
Make JsonPath Serializable

### ISSUE THREAD

**Issue by btiernay** [nebhale/JsonPath#11]
This will help out in a variety of contexts. In particular, I need to serialize `JsonPath` instances across hadoop nodes.

**Comment by nebhale** [comment]
Can you elaborate on this a little more?  What value is there in serializing `JsonPath`s?  Why would you do this rather than recompiling on each node?

**Comment by btiernay** [comment]
To make a long story short, the serialization process is out my control. But this is effectively what I am doing. But it would be more convenient to not have to. Any reason why you are hesitant? Btw, http://docs.oracle.com/javase/6/docs/api/java/util/regex/Pattern.html is serializable :)

**Comment by nebhale** [comment]
Simply because serialization is more than just marking a class as `Serializable`.  For a _good_ implementation it'll require quite a bit of custom logic to serialize all the types that sit under `JsonPath`.  It's not a trivial amount of work to implement, which is not to say that it won't happen.

**Comment by btiernay** [comment]
That's a fair point. I didn't realize there was a lot of types / state / work to do in this regard. Most of my usages of serialization these days is for transient transmission rather than long term storage, so I often forget about the intricacies of serialization design. 

Btw, back to the original reason for the request if you are interested: 

https://groups.google.com/d/msg/cascading-user/_NFnitPthkA/xj__ZKmRcJYJ

"Cascading serializes the Flow object graph and distributes it as part of the Hadoop job XML (or via the Distributed Cache, if they are too big). So as long as your data structure (map) is Serializable, it should work."

So, as it happens the `JsonPath` objects I'm using are in the transitive hull of the Flow object graph :)

**Comment by nebhale** [comment]
Can you give me a quick snippet of what you're doing with `JsonPath`?  Specifically, are you calling `JsonPath.compile()` and then storing that as a field in an instance?

**Comment by nebhale** [comment]
I've gone ahead and done an implementation of `Serializable` for JsonPath and there is a snapshot build available at https://oss.sonatype.org/content/repositories/snapshots/.  @btiernay, let me know if this works for you.

**Comment by btiernay** [comment]
Works well! Thanks once again Ben!

**Comment by btiernay** [comment]
Just curious if you will be cutting a new release. Thanks.

**Comment by nebhale** [comment]
I'd planned to do some work adding array slicing syntax in before the next release. However with the long Easter weekend, I don't know when I'm going to get to it. Would sooner be better for you?

**Comment by btiernay** [comment]
Sooner would be better, but I'm in no real rush. Array syntax would be cool :)

**Comment by nebhale** [comment]
1.2 released and should be available in central in the next couple of hours.
