### ISSUE TITLE
Update to use Jackson 2.x and expose JsonNode

### ISSUE THREAD

**Issue by btiernay** [nebhale/JsonPath#2]
Any chance of upgrading to the new Jackson 2.x line and supporting JsonNode directly? I think this would be a great addition.

Let me know.

Thanks for a great library!

**Comment by nebhale** [comment]
What exactly do you mean by supporting `JsonNode` directly?  [Looking at the code](https://github.com/nebhale/JsonPath/blob/master/src/main/java/com/nebhale/jsonpath/JsonPath.java#L105) I'd guess that you can just tell the read method that you want a `JsonNode.class` back and you'd get it.  The caveat being that I haven't tried this.

As to the 2.x upgrade, I'll get on that in the next couple of days.

**Comment by btiernay** [comment]
Thanks for upgrading :)

By  supporting `JsonNode` I mean having a way to both provide and return a `JsonNode` values. Thus, if I already have `JsonNode` instance, I could directly supply it to `JsonPath`:

```
import com.fasterxml.jackson.core.type.TypeReference;

JsonNode node =  createJsonNode();

List<JsonNode> names = JsonPath.read("$.name", node, new TypeReference<List<JsonNode>>() {});
```

This would return references to actual `JsonNodes` themselves, and not copies. This enables quite a few  interesting and powerful possiblities for dynamic applications. For instance, one could use this in an application that takes a list of json path expressions as metadata to dynamically filter a `JsonNode` structure. This is actually the usecase I'm most interested in.

**Comment by btiernay** [comment]
Btw, have you read: http://www.cowtowncoder.com/blog/archives/2011/08/entry_460.html ?

I'm sure Tatu Saloranta of Jackson would be very interested in your work (see the last paragraph in particular).

**Comment by nebhale** [comment]
Splitting the `JsonNode` part of this issue into #3.  Jackson 2 upgrade complete.
