### ISSUE TITLE
Support `JsonNode` as an input type

### ISSUE THREAD

**Issue by nebhale** [nebhale/JsonPath#3]
via @btiernay from #2:

---

Thanks for upgrading :)

By  supporting `JsonNode` I mean having a way to both provide and return a `JsonNode` values. Thus, if I already have `JsonNode` instance, I could directly supply it to `JsonPath`:

```
import com.fasterxml.jackson.core.type.TypeReference;

JsonNode node =  createJsonNode();

List<JsonNode> names = JsonPath.read("$.name", node, new TypeReference<List<JsonNode>>() {});
```

This would return references to actual `JsonNodes` themselves, and not copies. This enables quite a few  interesting and powerful possiblities for dynamic applications. For instance, one could use this in an application that takes a list of json path expressions as metadata to dynamically filter a `JsonNode` structure. This is actually the usecase I'm most interested in.

**Comment by nebhale** [comment]
@btiernay

Please checkout `master` and see if the changes in 9e9a41ee500d4b1fe9cebac8dc7a91b939456ec5 meet your needs.  I don't personally use JsonPath this way, so I'm interested if these limited changes are sufficient for your requirements.

**Comment by btiernay** [comment]
Wow, this is awesome and exactly what I was hoping for! I haven't run it myself, but I did take a look at your unit tests to see how it is used. 

I can think of many more useful features that could be added on top of this (filtering, transforming, shorthands), but that is for another day :)

Thanks again, I really appreciate the fast turn around time and you efforts.

One last thing. Any chance of releasing this to Maven central?

**Comment by nebhale** [comment]
No problem.  I kind of got this to where I needed it to be and then stopped work.  I'll close this issue out and open another one around Maven Central.

**Comment by btiernay** [comment]
Darn, looks as though I can't use this in the way I originally needed because of:

http://jackson-users.ning.com/forum/topics/jsonnode-findparent-method

Essentially, I overlooked the fact that in Jackson, you cannot query for the parent node. This means one would need to keep track of the parent during processing, or split the path into basePath and childPath components and process independently. Oh well.
