### ISSUE TITLE
Publish Artifacts to Maven Central

### ISSUE THREAD

**Issue by nebhale** [nebhale/JsonPath#4]
Publish artifacts to Maven Central.  Investigate using the [Sonatype OSS Repository](http://maven.apache.org/guides/mini/guide-central-repository-upload.html) to do this.  Split from #3.

**Comment by nebhale** [comment]
[Sonatype OSS JIRA issue](https://issues.sonatype.org/browse/OSSRH-5631)

**Comment by btiernay** [comment]
Thanks!
